### ISSUE TITLE
fatal error on Woocommerce 6.1.1

### ISSUE THREAD

**Issue by chiareu** [finalwebsites/woo-sendy#1]
An error of type E_ERROR was caused in line 41 of the file .../wp-content/plugins/woocommerce/includes/class-wc-integrations.php. Error message: Uncaught Error: Class 'FWS_Woo_Sendy_Integration' not found in .../wp-content/plugins/woocommerce/includes/class-wc-integrations.php:41
Stack trace:
#0 .../wp-content/plugins/woocommerce/includes/class-woocommerce.php(620): WC_Integrations->__construct()
#1 .../public_html/wp-includes/class-wp-hook.php(303): WooCommerce->init()
#2 .../wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#3 .../wp-includes/plugin.php(470): WP_Hook->do_action()
#4 .../wp-settings.php(578): do_action()
#5 .../wp-config.php(102): require_once('/home/xxxx...')
#6 .../wp-load.php(50): require_once('/home/xxxx...')
#7 .../wp-admin/admin.php(34): require_once('/home/xxxx...')
#8 .../wp-admin/plugins.php(10): require_once('/home/xxxx...')
#9 {m

**Comment by finalwebsites** [comment]
@chiareu 
Thanks for the warning, right now I don't have many projects using Sendy. But I'm using the same integration for other EM providers. I need to check/fix this before the next update.
